In [7]:
import os
import pandas as pd
from pathlib import Path

In [14]:
PROJ_PATH = Path(os.getcwd()).parent
DATA_PATH = PROJ_PATH / 'Data'

In [15]:
team_stats = pd.read_csv(DATA_PATH / 'Tournament_Team_Data.csv')
game_results = pd.read_csv(DATA_PATH / 'Tournament_Game_Results.csv')

In [18]:
# Select columns from team_stats
team_stats

,YEAR,SEED,TEAM,ROUND,KENPOM ADJUSTED EFFICIENCY,KENPOM ADJUSTED OFFENSE,KENPOM ADJUSTED DEFENSE,KENPOM ADJUSTED TEMPO,BARTTORVIK ADJUSTED EFFICIENCY,BARTTORVIK ADJUSTED OFFENSE,...,OP ASSIST %,OP O REB %,OP D REB %,BLOCKED %,TURNOVER % DEFENSE,WINS ABOVE BUBBLE,WIN %,POINTS PER POSSESSION OFFENSE,POINTS PER POSSESSION DEFENSE,TEAM.1
0,2023,1,Alabama,0,26.9363,115.832,88.8960,72.7700,27.588,116.981,...,41.8,27.6,66.2,11.4,16.0,10.6,85.294118,1.106,0.922,Alabama
1,2023,1,Houston,0,29.8743,118.854,88.9798,63.3827,28.290,118.260,...,53.6,27.4,62.9,6.6,22.0,8.4,91.176471,1.158,0.872,Houston
2,2023,1,Kansas,0,23.1345,114.703,91.5684,69.2256,21.359,113.750,...,46.2,28.3,71.6,7.3,20.2,10.5,79.411765,1.062,0.963,Kansas
3,2023,1,Purdue,0,24.7732,119.951,95.1774,64.2174,25.247,119.495,...,51.5,23.3,61.7,8.6,15.4,9.2,85.294118,1.135,0.974,Purdue
4,2023,2,Arizona,0,22.8757,120.078,97.2023,72.2672,23.914,120.450,...,49.4,26.2,68.9,9.3,16.9,7.5,82.352941,1.134,0.981,Arizona
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1006,2008,16,Mississippi Valley St.,64,-15.0000,92.100,107.1000,62.4000,-15.300,90.000,...,50.4,34.5,67.5,9.1,22.9,-10.0,50.000000,0.927,0.997,Mississippi Valley St.
1007,2008,16,Mount St. Mary's,64,-1.0000,99.000,100.1000,65.2000,-1.800,97.300,...,47.8,33.0,70.0,7.5,22.0,-9.5,56.250000,1.006,0.968,Mount St. Mary's
1008,2008,16,Portland St.,64,5.8000,108.400,102.6000,65.8000,3.500,105.300,...,54.8,31.3,66.0,6.3,21.5,-3.4,70.000000,1.088,1.003,Portland St.
1009,2008,16,UT Arlington,64,-2.0000,101.100,103.1000,68.0000,-2.100,99.100,...,56.0,30.5,68.2,7.6,20.8,-7.0,60.710000,1.006,0.971,UT Arlington
1010,2008,16,Coppin St.,68,-14.2000,92.400,106.7000,62.2000,-15.400,90.200,...,60.5,38.5,68.0,11.3,25.2,-13.0,41.180000,0.907,1.013,Coppin St.

In [17]:
# Drop ['ROUND', 'WSCORE', 'LSCORE']
# Create field 'UPSET' (if 'WSEED' > 'LSEED' then 'yes')    FIGURE OUT WHAT TO DO WITH EQUAL SEEDS
# Create 'BETTER_SEED' and 'WORSE_SEED' fields
game_results

,YEAR,ROUND,WSEED,WTEAM,WSCORE,LSEED,LTEAM,LSCORE
0,2021,6,1,Baylor,86,1,Gonzaga,70
1,2021,5,1,Gonzaga,93,11,UCLA,90
2,2021,5,1,Baylor,78,2,Houston,59
3,2021,4,2,Houston,67,12,Oregon State,61
4,2021,4,1,Baylor,81,3,Arkansas,72
...,...,...,...,...,...,...,...,...
2312,1985,1,3,North Carolina State,65,14,Nevada,56
2313,1985,1,4,Ohio State,75,13,Iowa State,64
2314,1985,1,1,Oklahoma,96,16,North Carolina A&T,83
2315,1985,1,7,Notre Dame,79,10,Oregon State,70
2316,1985,1,2,North Carolina,76,15,Middle Tennessee State,57